### ISSUE TITLE
Просьба отключить Sentry

### ISSUE THREAD

**Issue by turikhay** [VidTuGit/BetterTL#1]
Привет. К нам в Sentry [начали приходить](https://imgur.com/a/eyQsZdK) ошибки из этого форка
Можешь отключить их передачу? :)

**Comment by VidTuGit** [comment]
оу, ок.
он ваще не для паблик использования))

**Comment by VidTuGit** [comment]
п.с. он не для паблик использования, потому что ваш лаунчер нельзя распространять модифицированным.
